### PR TITLE
[feat] HC subscription

### PR DESCRIPTION
**Pull request by romualdr**
## Done

- Get HC informations ( with since / days for month / prepaid months )
- Subscribe to HC
- Persist information to database
## Missing
- HC informations for player (badges / dance)
- HC furniture

### CODE REVIEW

**Comment by romualdr** [comment]
well, i just noticed a mistake just before `free(club)`. I check if the value is null, but this check is actually useless. I removed it from my code and i will publish a patch soon.

**Comment by emansom** [comment]
Nice! :raised_hands:

**Comment by emansom** [comment]
Could you re-add that comment to the code on why you free the first value read?
Something akin to;
```
We ignore the first value, as multiple club subscriptions only got implemented in much later versions
```

**Comment by Quackster** [comment]
Looks good, only problem I have is that HC is still incomplete because month gifts exist, but I can code them myself if that's too much hassle for you, and I don't mind either, since it's my project.

Thanks for the pull request as I really appreciate your contributions! 😃

**Comment by romualdr** [comment]
Yes ! Well i thought about implementing them, but i don't know how you want to handle the gifts informations

I started working on this:
- A new table called `club_gifts`: `{ 'description_id', 'month', 'quantity' }`
- A new database query `club_gifts_query`
- Added a `club_last_redeemed_month_gift` ( or smthg like that ) to the player
- Added a `club_gifts` List * loaded at the init of `Item manager` ( and freed in dispose ) 

- I was planning to check the difference in months between `club_last_redeemed_month_gift` and `since` with the following logic (pseudo code jibberish)
```
// This is useful if the player does not connect every month & the gifts wasn't redeemed
// This way, we will always give all the gifts the player should have get for HC 
if (club_expiration > now ?)
   since_month = now - club_subscribe
else
   since_month = club_expiration - club_subscribe

if (club_last_redeemed_month_gift != since_month)
  for (item = club_get_all_furnitures_for(since_month,  club_last_redeemed_month_gift))
    player_give_item(item) // and add the club_gift.message text
player.club_last_redeemed_month_gift = since_month

// Reset since_month && club_last_redeemed_month_gift with club_subscribe if the user is not HC anymore.
```

What do you think ?

I've left some TODO in the code to not forget about the uncompleteness of HC for now :)

**Comment by romualdr** [comment]
I made a mistake in my message 😅 I actually called it `definition_id` to fit to the `items` table.

I added the `club_last_redeemed_month_gift` variable to the player to be able to catch up with club gifts. I didn't wanted to implement a task (like a cron job) each day.  I was about to check the gift each time the user connect - in the `player_refresh_club` function - but doing this introduces two problems: 

• How do we know if we already gave an item to this player ? We could scan all his items, but that introduces a lot of more problems (if the user trades the item for instance).
• If the user connects like two / three or eleven months after his first HC subscription, we have to know which monthly gift he had to calculate the missing gifts.

In order to solve this, saving the last monthly gift redeemed make this task pretty trivial, since we always have to calculate the number of month the user has been subscribed to HC. The difference between these two numbers gives us the gifts that wasn't redeemed yet, so we can give them to th player, and save the actual month - or set it to 0 if his subscription has expired.

Do you get the point ? I'm open to improvements without adding `club_last_redeemed_month_gift` but i couldn't find a solution to this without it :/

**Pull request merged**
