### PR TITLE
Implement SSO

### PR DESCRIPTION
**Pull request by emansom**

### CODE REVIEW

**Comment by emansom** [comment]
Reverted the figure change. :sweat_smile:

**Comment by emansom** [comment]
P.S: using `player_manager_destroy_session_by_id` for the login is a good idea, else you will end up with duplicates by logging in with the same user and entering a room.

**Comment by Quackster** [comment]
Thanks! 👍 

Also I have plans to go straight to V26 after this, once all the V18 features are implemented, because I like widescreen. 🙂

Also make sure you keep your fork up to date, because I add features to it almost every day.

**Comment by Quackster** [comment]
So I plan to ultimately have two server versions, or maybe make this one server support both versions (should be easy anyways), but that's in the future, better to not worry about that now. 😄

**Comment by emansom** [comment]
I'm gonna keep my fork V21 no matter what, I love the old console too much. :wink:

To keep it compatible with both the old and newer version, in the future, we'll need to identify which packets have structural changes, and then implement both versions for each those packets and have an configuration option that toggles between those two versions (or better yet; user configurable per column in database :eyes:)

It would be cool to mirror NexusServer's and Bluedot/IHI's functionality by being feature-agnostic. :raised_hands:

**Pull request merged**
