### PR TITLE
Implements room voting, SQLite fixes/workarounds, log outgoing packets

### PR DESCRIPTION
**Pull request by emansom**
I kept getting SQLite `database is locked` errors, as there are now multiple threads (roller task and server thread) accessing the database. I worked around this by enabling [WAL mode](https://www.sqlite.org/wal.html) and increasing the [timeouts](https://www.sqlite.org/c3ref/busy_timeout.html). This however, is a temporary workaround and what we really need is mutexes/atomics/locks in the database queries functions, so that we never access the same database table at the same time.

Room voting has been implemented in the way Sulake intended it to. In most other emulators when you vote, other users that haven't voted yet; can't vote after that, because their vote UI is gone as the packet got broadcasted to the whole room. (Holograph does this)

Older clients should ignore the speech bubbles packets, making it a no-op. Feel free to delete if needed.

Added the logging of outgoing messages, I hope your terminal is fast enough :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by emansom** [comment]
P.S: I've been playing around with [gdbgui](https://gdbgui.com/), pretty cool debugging tool. Helps when debugging segmentation faults. :smile: 

P.P.S; there's a race condition in the roller_task, sometimes it tries to move a user, while that user is currently moving to another room, resulting in accessing a null pointer.

**Comment by emansom** [comment]
I'm now forcing SQLite to use [serialized mode](https://www.sqlite.org/threadsafe.html), if I understand the documentation of SQLite correctly; this should for now resolve the contention issues.

**Comment by emansom** [comment]
As per [the docs](https://www.sqlite.org/c3ref/prepare.html) advisement `The preferred routine to use is sqlite3_prepare_v2(). The sqlite3_prepare() interface is legacy and should be avoided.`

**Comment by emansom** [comment]
`database is locked` errors might still happen with WAL and serialized, see this [post](https://stackoverflow.com/a/17124940). In order to solve this completely we need to wrap a lock/mutex around the sqlite3 functions inside the query functions. Then there's only one connection open at a time.

**Comment by emansom** [comment]
Switching to multi-thread mode as the serialized mode is safer, but blows up the callee with `SQL_BUSY` errors.

As per the [wiki](https://www.sqlite.org/threadsafe.html) `Multi-thread. In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.` Note **single**. We do not pass around database connections between threads, therefore should be safe.

I hope this solves the `database is locked` errors. Testing will tell. :smile:

**Comment by Quackster** [comment]
Hmm, I think long term will be better to use PostgreSQL, otherwise the source file with all these SQLite queries will just continue to grow and grow until the amount of work required to convert over to PostgreSQL becomes exponentially huge to the point where it was regrettable to not do it sooner.

**Comment by Quackster** [comment]
Also this may fix the race condition when the roller task attempts to slide a user who is changing rooms: https://github.com/Quackster/Kepler/commit/e1aec1c11cd3a34ddd9e3a93b1592d4eb73b9722

**Comment by emansom** [comment]
I'd prefer MySQL/MariaDB, as the community has more knowledge of that DBMS. There has to be better bindings out there.

**Pull request merged**
