### PR TITLE
Make it buildable on MacOS

### PR DESCRIPTION
**Pull request by romualdr**
Make it buildable on MacOS

### CODE REVIEW

**Comment by emansom** [comment]
I don't see how this would help. Could you eleborate on what went wrong when building?

**Comment by romualdr** [comment]
Sure.

On OSX __useconds_t and __sighandler_t doesn't exist. They are named useconds_t and sig_t.

This is why you need to perform a typedef for the OSX platform. Without them the build gives this result:

```
/Users/romuald/private/Kepler/src/util/stringbuilder.c:15:36: warning: 'memset' call operates on objects of type 'char' while the size is based on a different type 'char *' [-Wsizeof-pointer-memaccess]
    memset(sb->data, 0, sizeof(sb->data));
           ~~~~~~~~            ~~~~^~~~
/Users/romuald/private/Kepler/src/util/stringbuilder.c:15:36: note: did you mean to provide an explicit length?
    memset(sb->data, 0, sizeof(sb->data));
                               ~~~~^~~~
/Users/romuald/private/Kepler/src/util/threading.c:53:13: error: use of undeclared identifier '__useconds_t'
    usleep((__useconds_t) run->millis * 1000);
            ^
1 error generated.
make[3]: *** [CMakeFiles/Kepler.dir/src/util/threading.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
1 warning generated.
/Users/romuald/private/Kepler/src/main.c:28:21: error: use of undeclared identifier '__sighandler_t'
    signal(SIGINT, (__sighandler_t) exit_program); // Handle cleanup on Ctrl-C
                    ^
```

And with this fix, it works fine.

**Comment by emansom** [comment]
Could you move it to `main.h` and remove the redundant checks for other OSes?

**Comment by emansom** [comment]
Split it up. Add this to `threading.h`

```
#if __APPLE__
    #define __useconds_t useconds_t
#endif
```

**Comment by emansom** [comment]
Local testing with using `usecond_t` instead of `__useconds_t` and dropping the cast on the `signal()` call works too. That seems like the proper fix

**Comment by romualdr** [comment]
Make sense ! I will make those change tomorrow.
How about `__sighandler_t` ? I think maybe `sig_t` is really OSX specific.

**Comment by Quackster** [comment]
I'll wait until you make the changes before I merge the pull request. 😜

**Comment by romualdr** [comment]
Yes ! Great solution @emansom 👍 - it works fine with no `typedef` required.

I did a `rebase` and now it looks like I broke my branch - the changelog / commits are weird.

I created another clean PR here : #20

**Pull request closed without merging**
