### PR TITLE
Vouchers [WIP]

### PR DESCRIPTION
**Pull request by killerloader**
This adds voucher functionality (so you can add vouchers into the vouchers table in SQL, and then they can be redeemed in-game)

I'm unsure what to do for the .sql file, I could simply add the new "vouchers" table to kepler.sql
but I'm confused about the migrations folder with SQL files in it.

The SQL table uses a unique varchar column "VoucherCode", and an INT column "Credits"

This is my first time using java, it took me ages to figure out how to even build the project.
(I use C++ & C#)
So tell me if there is anything I should change :)

Relatively small amount of changes, but took me a long time because I lack experience with java.
Also I was programming in notepad++, so had no intellisense :(

### CODE REVIEW

**Comment by killerloader** [comment]
Just realised that it needs to be able to redeem furniture as well, so gonna keep working on it a little bit more.

**Comment by Quackster** [comment]
No problem. Thanks for the contribution effort. 😃

**Comment by killerloader** [comment]
I think the logic is all done now. Though I don't know if it's accurate to how habbo should work.
What do you want me to do about the new SQL tables? Should I just add them to the kepler.sql file?

**Comment by Quackster** [comment]
Wow I can't believe I missed your comment, the pull request looks good, have you tested it yet?

**Comment by Quackster** [comment]
Also you can add the SQL changes in the **update.1.21.sql** file under /tools/migrations/

**Comment by killerloader** [comment]
No problem. Thanks for the merge!
Have tested and seems to work on my end. Doesn't seem to open the hand atm on my client when you redeem furni, but the furni does get added. But I think I broke some parts of my hh_interface.

Was going to say wait until I test on an unaltered client, but should be fine 😃 Thanks!

Also, I have to use:
id "org.jetbrains.intellij" version "0.4.9" 
for compilation to work atm, otherwise I get compilation errors

**Comment by Quackster** [comment]
Okay, also you will be added to the list of contributors in the :about

Also I hope you don't mind but I changed the SQL table schema a tiny bit so watch out for that when you want to use the voucher system. :)

**Comment by killerloader** [comment]
Kool thanks!
I'll take a look, and hopefully if I add any more features I don't give you too much more work fixing it up hahaha 😄

**Pull request merged**
